### ISSUE TITLE
It fails to compile with external lxqt-wallet-4.0.2

### ISSUE THREAD

**Issue by PPN-SD** [mhogomchungu/zuluCrypt#242]
Hi,

I got failures when trying to build with external lxqt-wallet-4.0.2 (because I want Qt6 _and_ KF6 support) : 

```
[FAILED: [code=1] [plugins/gpg/gpg 
: && /usr/bin/x86_64-pc-linux-gnu-g++ -O2 -pipe -march=znver2 -frecord-gcc-switches -Wl,-O1 -Wl,--as-needed -Wl,-z,pack-relative-relocs -Wl,--dependency-file=plugins/gpg/CMakeFiles/gpg.dir/link.d plugins/gpg/CMakeFiles/gpg.dir/gpg_autogen/mocs_compilation.cpp.o plugins/gpg/CMakeFiles/gpg.dir/main.cpp.o plugins/gpg/CMakeFiles/gpg.dir/gpg_autogen/5TB7W6GN3K/qrc_icon.cpp.o -o plugins/gpg/gpg  -Wl,-rpath,/var/tmp/portage/app-crypt/zulucrypt-7.1.0/work/zuluCrypt-7.1.0_build/zuluCrypt-cli:  plugins/libplugin.a  zuluCrypt-gui/sharedObjects/libsharedObject.a  -lgcrypt  -llxqt-wallet  -lblkid  /usr/lib64/libQt6Network.so.6.10.1  external_libraries/tasks/libmhogomchungu_task.a  /usr/lib64/libQt6Widgets.so.6.10.1  /usr/lib64/libQt6Gui.so.6.10.1  /usr/lib64/libOpenGL.so  /usr/lib64/libQt6Core.so.6.10.1  zuluCrypt-cli/libzuluCryptPluginManager.so.1.0.0  zuluCrypt-cli/libSocket.a  zuluCrypt-cli/libProcess.a  -pthread  zuluCrypt-cli/libString.a  /usr/lib64/libblkid.so && :
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: zuluCrypt-gui/sharedObjects/libsharedObject.a(utility.cpp.o): in function `utility::getKey(LXQt::Wallet::Wallet&, QString const&, QString const&)':
utility.cpp:(.text+0x16243): undefined reference to `LXQt::Wallet::walletExists(LXQt::Wallet::BackEnd, QString const&, QString const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: zuluCrypt-gui/sharedObjects/libsharedObject.a(favorites2.cpp.o): in function `Task::detail::ThreadHelper<bool, favorites2::walletOpts::getStatus()::{lambda()#1}>::run()':
favorites2.cpp:(.text+0x370): undefined reference to `LXQt::Wallet::backEndIsSupported(LXQt::Wallet::BackEnd)'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: zuluCrypt-gui/sharedObjects/libsharedObject.a(favorites2.cpp.o): in function `favorites2::walletOpts::status::status()':
favorites2.cpp:(.text+0x1f00): undefined reference to `LXQt::Wallet::backEndIsSupported(LXQt::Wallet::BackEnd)'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: zuluCrypt-gui/sharedObjects/libsharedObject.a(favorites2.cpp.o): in function `QtPrivate::QCallableObject<favorites2::favorites2(QWidget*, secrets&, std::function<void ()>)::{lambda(bool)#1}, QtPrivate::List<bool>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*)':
favorites2.cpp:(.text+0x7a3f): undefined reference to `LXQt::Wallet::walletExists(LXQt::Wallet::BackEnd, QString const&, QString const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: zuluCrypt-gui/sharedObjects/libsharedObject.a(favorites2.cpp.o): in function `favorites2::favorites2(QWidget*, secrets&, std::function<void ()>)':
favorites2.cpp:(.text+0x93a8): undefined reference to `LXQt::Wallet::backEndIsSupported(LXQt::Wallet::BackEnd)'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: favorites2.cpp:(.text+0x9c6a): undefined reference to `LXQt::Wallet::walletExists(LXQt::Wallet::BackEnd, QString const&, QString const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: zuluCrypt-gui/sharedObjects/libsharedObject.a(favorites2.cpp.o): in function `std::_Function_handler<bool (), Task::detail::ThreadHelper<bool, favorites2::walletOpts::getStatus()::{lambda()#1}>::ThreadHelper(favorites2::walletOpts::getStatus()::{lambda()#1})::{lambda()#3}>::_M_invoke(std::_Any_data const&)':
favorites2.cpp:(.text+0xfca): undefined reference to `LXQt::Wallet::backEndIsSupported(LXQt::Wallet::BackEnd)'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: zuluCrypt-gui/sharedObjects/libsharedObject.a(secrets.cpp.o): in function `secrets::backends::get(LXQt::Wallet::BackEnd)':
secrets.cpp:(.text+0x8e8): undefined reference to `LXQt::Wallet::getWalletBackend(LXQt::Wallet::BackEnd)'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: zuluCrypt-gui/sharedObjects/libsharedObject.a(secrets.cpp.o): in function `secrets::wallet::getKey(QString const&, QWidget*)':
secrets.cpp:(.text+0x1ed1): undefined reference to `LXQt::Wallet::walletExists(LXQt::Wallet::BackEnd, QString const&, QString const&)'
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: plugins/gpg/gpg: protected symbol `_ZN4LXQt6Wallet12walletExistsENS0_7BackEndERK7QStringS4_' isn't defined
/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status

```

[BUILD.log](https://github.com/user-attachments/files/24076072/BUILD.log)

**Comment by PPN-SD** [comment]
The cleaning of QT5/KF5 starts in many distributions, do you need more context for this issue?

**Comment by mhogomchungu** [comment]
What distribution are you using and can you point me to an installation image i can use to locally test?

**Comment by PPN-SD** [comment]
Gentoo here, but lxqt-wallet is not packaged in the official repo. Once this issue is resolved, it will be added: [lxqt-wallet-4.0.2.ebuild](https://bpa.st/UZAQ)

**Comment by PPN-SD** [comment]
Anyway, as far as I can remember, the upstream version of lxqt‑wallet differs from what is included here.

**Comment by mhogomchungu** [comment]
This problem should now be fixed and you can use the fixed version by updating the library from Gentoo repository.

**Comment by PPN-SD** [comment]
This PR I guess:
https://github.com/lxqt/lxqt_wallet/pull/63

**Comment by PPN-SD** [comment]
> This problem should now be fixed and you can use the fixed version by updating the library from Gentoo repository.

Indeed. Fixed.
